# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

defaults: &dockerAndWorkingDirectory
    working_directory: ~/react-boilerplate
    docker:
        - image: circleci/node:7.10

defaults: &npmInstall
    name: Installing all dependencies
    command: npm install

version: 2
jobs:
    test-job:
        <<: *dockerAndWorkingDirectory
        steps:
            - checkout
            - restore_cache:
                keys:
                    - app-dependencies-v1-{{ checksum "package.json" }}
            - run:
                <<: *npmInstall
            - save_cache:
                key: app-dependencies-v1-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Running the tests
                command: npm run test
    build-job:
        <<: *dockerAndWorkingDirectory
        steps:
            - checkout
            - restore_cache:
                keys:
                    - app-dependencies-v2-{{ checksum "package.json" }}
                    - app-dependencies-v1-{{ checksum "package.json" }}
            - run:
                <<: *npmInstall
            - save_cache:
                key: app-dependencies-v2-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Build the project
                command: npm run build
    deploy-job:
        <<: *dockerAndWorkingDirectory
        steps:
            - checkout
            - restore_cache:
                keys:
                    - app-dependencies-v2-{{ checksum "package.json" }}
                    - app-dependencies-v1-{{ checksum "package.json" }}
            - run:
                <<: *npmInstall
            - run:
                name: Build the project
                command: npm run build
            - run:
                name: Deploy to Digital Ocean
                command: npm run deploy
workflows:
    version: 2
    build-deploy:
        jobs:
            - test-job
            - build-job:
                requires:
                    - test-job
            - deploy-job:
                requires:
                    - build-job
